--------------------------------------------------------
--  DDL for Table TD_TRAIN_CARTE
--------------------------------------------------------

Insert into HR.TD_TRAIN_CARTE (CD_CARTE,TYPE_CARTE,DESC_CARTE,PRIX) values ('CAJ','COMMERCIALE','CARTE AVANTAGE JEUNE','49');
Insert into HR.TD_TRAIN_CARTE (CD_CARTE,TYPE_CARTE,DESC_CARTE,PRIX) values ('CAS','COMMERCIALE','CARTE AVANTAGE SENIOR','49');
Insert into HR.TD_TRAIN_CARTE (CD_CARTE,TYPE_CARTE,DESC_CARTE,PRIX) values ('CAA','COMMERCIALE','CARTE AVANTAGE ADULTE','49');
Insert into HR.TD_TRAIN_CARTE (CD_CARTE,TYPE_CARTE,DESC_CARTE,PRIX) values ('CAW','COMMERCIALE','CARTE AVANTAGE WEEKEND','49');
Insert into HR.TD_TRAIN_CARTE (CD_CARTE,TYPE_CARTE,DESC_CARTE,PRIX) values ('CF','FIDELITE','CARTE DE FIDELITE','0');
