--------------------------------------------------------
--  DDL for Table TF_TRAIN_COMMANDE
--------------------------------------------------------

Insert into HR.TF_TRAIN_COMMANDE (CD_COMMANDE,CD_EMAIL,CD_TRAIN,CD_VOYAGE,CD_CARTE,QUANTITE,DATE_ACHAT,MONTANT,DATE_VOYAGE,CODE_PAYS) values ('1000','23456','TG','11','CAJ','1',to_date('03/11/21','DD/MM/RR'),'80',to_date('01/02/20','DD/MM/RR'),null);
Insert into HR.TF_TRAIN_COMMANDE (CD_COMMANDE,CD_EMAIL,CD_TRAIN,CD_VOYAGE,CD_CARTE,QUANTITE,DATE_ACHAT,MONTANT,DATE_VOYAGE,CODE_PAYS) values ('1001','23457','OUI','89','CAS','1',to_date('04/10/21','DD/MM/RR'),'10',to_date('02/02/20','DD/MM/RR'),null);
Insert into HR.TF_TRAIN_COMMANDE (CD_COMMANDE,CD_EMAIL,CD_TRAIN,CD_VOYAGE,CD_CARTE,QUANTITE,DATE_ACHAT,MONTANT,DATE_VOYAGE,CODE_PAYS) values ('1002','23458','TR','41','CAA','1',to_date('05/09/21','DD/MM/RR'),'55',to_date('03/02/20','DD/MM/RR'),null);
Insert into HR.TF_TRAIN_COMMANDE (CD_COMMANDE,CD_EMAIL,CD_TRAIN,CD_VOYAGE,CD_CARTE,QUANTITE,DATE_ACHAT,MONTANT,DATE_VOYAGE,CODE_PAYS) values ('1003','23459','EUR','21','CAW','1',to_date('06/08/21','DD/MM/RR'),'100',to_date('04/02/20','DD/MM/RR'),null);
Insert into HR.TF_TRAIN_COMMANDE (CD_COMMANDE,CD_EMAIL,CD_TRAIN,CD_VOYAGE,CD_CARTE,QUANTITE,DATE_ACHAT,MONTANT,DATE_VOYAGE,CODE_PAYS) values ('1004','23460','THA','15','CF','1',to_date('07/07/21','DD/MM/RR'),'98',to_date('05/02/20','DD/MM/RR'),null);
Insert into HR.TF_TRAIN_COMMANDE (CD_COMMANDE,CD_EMAIL,CD_TRAIN,CD_VOYAGE,CD_CARTE,QUANTITE,DATE_ACHAT,MONTANT,DATE_VOYAGE,CODE_PAYS) values ('1005','23461','INT','51','CAJ','1',to_date('08/06/21','DD/MM/RR'),'66',to_date('06/02/20','DD/MM/RR'),null);
Insert into HR.TF_TRAIN_COMMANDE (CD_COMMANDE,CD_EMAIL,CD_TRAIN,CD_VOYAGE,CD_CARTE,QUANTITE,DATE_ACHAT,MONTANT,DATE_VOYAGE,CODE_PAYS) values ('1006','23462','TG','11','CAS','1',to_date('09/02/21','DD/MM/RR'),'80',to_date('07/02/20','DD/MM/RR'),null);
Insert into HR.TF_TRAIN_COMMANDE (CD_COMMANDE,CD_EMAIL,CD_TRAIN,CD_VOYAGE,CD_CARTE,QUANTITE,DATE_ACHAT,MONTANT,DATE_VOYAGE,CODE_PAYS) values ('1007','23463','OUI','89','CAA','1',to_date('10/04/21','DD/MM/RR'),'10',to_date('08/02/20','DD/MM/RR'),null);
Insert into HR.TF_TRAIN_COMMANDE (CD_COMMANDE,CD_EMAIL,CD_TRAIN,CD_VOYAGE,CD_CARTE,QUANTITE,DATE_ACHAT,MONTANT,DATE_VOYAGE,CODE_PAYS) values ('1008','23464','TR','41','CAW','1',to_date('11/09/21','DD/MM/RR'),'55',to_date('09/02/20','DD/MM/RR'),null);
Insert into HR.TF_TRAIN_COMMANDE (CD_COMMANDE,CD_EMAIL,CD_TRAIN,CD_VOYAGE,CD_CARTE,QUANTITE,DATE_ACHAT,MONTANT,DATE_VOYAGE,CODE_PAYS) values ('1009','23465','EUR','21','CF','1',to_date('12/01/21','DD/MM/RR'),'100',to_date('10/02/20','DD/MM/RR'),null);
Insert into HR.TF_TRAIN_COMMANDE (CD_COMMANDE,CD_EMAIL,CD_TRAIN,CD_VOYAGE,CD_CARTE,QUANTITE,DATE_ACHAT,MONTANT,DATE_VOYAGE,CODE_PAYS) values ('1010','23466','THA','15','CAJ','1',to_date('13/06/21','DD/MM/RR'),'98',to_date('11/02/20','DD/MM/RR'),null);
Insert into HR.TF_TRAIN_COMMANDE (CD_COMMANDE,CD_EMAIL,CD_TRAIN,CD_VOYAGE,CD_CARTE,QUANTITE,DATE_ACHAT,MONTANT,DATE_VOYAGE,CODE_PAYS) values ('1011','23456','TG','51','CAS','1',to_date('14/06/21','DD/MM/RR'),'66',to_date('12/02/20','DD/MM/RR'),null);
Insert into HR.TF_TRAIN_COMMANDE (CD_COMMANDE,CD_EMAIL,CD_TRAIN,CD_VOYAGE,CD_CARTE,QUANTITE,DATE_ACHAT,MONTANT,DATE_VOYAGE,CODE_PAYS) values ('1012','23457','OUI','11','CAA','1',to_date('15/03/21','DD/MM/RR'),'80',to_date('13/02/20','DD/MM/RR'),null);
Insert into HR.TF_TRAIN_COMMANDE (CD_COMMANDE,CD_EMAIL,CD_TRAIN,CD_VOYAGE,CD_CARTE,QUANTITE,DATE_ACHAT,MONTANT,DATE_VOYAGE,CODE_PAYS) values ('1013','23458','TR','89','CAW','1',to_date('16/05/21','DD/MM/RR'),'10',to_date('14/02/20','DD/MM/RR'),null);

